[package]
name = "registration"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.40", features = ["std", "clock"], default-features = false }
getch-rs = "0.2.0"
local-ip-address = "0.6.3"
postgres = "0.19.10"
postgres-types = { version = "0.2.9", features = ["derive"] }
tiny_http = "0.12.0"
